<?php
/**
 * @var \Jleagle\Steam\Application\Views\ApiView $this
 */
?>

<div class="page-header">
  <h1>API</h1>
</div>

<?= $this->getAd() ?>

<p>If you want to show top user data on your website, you can use the following
   JSON endpoints.</p>
<p>Please be respectful by caching the data and linking back to us.</p>

<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
    <tr>
      <th width="15%">Content</th>
      <th>Endpoint</th>
    </tr>
    </thead>
    <tr>
      <td nowrap="nowrap">Users by levels</td>
      <td><?= $this->getPath() ?>/level</td>
    </tr>
    <tr>
      <td nowrap="nowrap">Users by games</td>
      <td><?= $this->getPath() ?>/games</td>
    </tr>
    <tr>
      <td nowrap="nowrap">Users by badges</td>
      <td><?= $this->getPath() ?>/badges</td>
    </tr>
    <tr>
      <td nowrap="nowrap">Users by time</td>
      <td><?= $this->getPath() ?>/time</td>
    </tr>
    <tr>
      <td nowrap="nowrap">Users by friends</td>
      <td><?= $this->getPath() ?>/friends</td>
    </tr>
  </table>
</div>
