<?php
/**
 * @var \Jleagle\Steam\Application\Views\AppListView $this
 */

use Jleagle\Steam\Application\Enums\AppTypeEnum;

?>

<div class="page-header">
  <h1>
    Apps
    <small class="pull-right"><?= $this->getCount() ?> Apps</small>
  </h1>
</div>

<?= $this->getAd() ?>

<form style="margin-bottom: 20px;" method="get" action="/apps">
  <div class="input-group">
    <input name="search" type="text" class="form-control" placeholder="Search"
           value="<?= $this->getSearch() ?>" required="required"
           pattern=".{<?= $this->getMin() ?>,}"
           title="<?= $this->getMin() ?> characters minimum.">
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit">Search</button>
    </span>
  </div>
  <?= $this->getCheckBoxes() ?>
</form>

<div class="table-responsive">
  <table class="table table-striped table-condensed">
    <thead>
    <tr>
      <th>Game</th>
      <th>Type</th>
      <th class="hidden-xs">Added</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->getApps() as $game)
    {
      ?>
      <tr>
        <td><a href="/apps/<?= $game->id ?>"><?= $game->name ?: '-' ?></a></td>
        <td><?= AppTypeEnum::getDisplayValue($game->type) ?></td>
        <td class="hidden-xs">
          <?= date('Y-m-d H:i:s', strtotime($game->created_at)); ?>
        </td>
      </tr>
      <?php
    }
    ?>
    </tbody>
  </table>
</div>
