<?php
/**
 * @var \Jleagle\Steam\Application\Views\DonateView $this
 */
?>

<div class="page-header">
  <h1>Donate</h1>
</div>

<?= $this->getAd() ?>

<p>If you would like to help us out at Steam Ranks, please think about
   donating.</p>
<p>Donating will cover the server costs as well as removing adverts, Thanks.</p>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
  <input type="hidden" name="cmd" value="_s-xclick">
  <input type="hidden" name="hosted_button_id" value="6GGLQLK27382E">
  <input type="image" src="/img/paypal.jpg" name="submit" height="50">
</form>
