<?php
/**
 * @var \Jleagle\Steam\Application\Views\UserNotFound $this
 */
?>

<div class="page-header">
  <h1>No User Found</h1>
</div>

<?= $this->getAd() ?>

<p>Sorry, we cant find "<?= $this->getSearch() ?>". Pleae make sure you are searching in the correct format.</p>
<p>Currently we are able to search for th following things:</p>

<div class="row">
  <div class="col-xs-4">
    <h4>Vanity Username</h4>
    <blockquote>jimeagle</blockquote>
  </div>
  <div class="col-xs-4">
    <h4>Community ID</h4>
    <blockquote>76561197985756607</blockquote>
  </div>
  <div class="col-xs-4">
    <h4>Stead ID</h4>
    <blockquote>STEAM_0:0:4180232</blockquote>
  </div>
  <div class="col-xs-4">
    <h4>Vanity URL</h4>
    <blockquote>http://steamcommunity.com/id/jimeagle/</blockquote>
  </div>
  <div class="col-xs-4">
    <h4>User ID</h4>
    <blockquote>25490879</blockquote>
  </div>
</div>
