<?php
/**
 * @var \Jleagle\Steam\Application\Views\UserView $this
 */
?>

<div class="page-header">
  <?php if(!$this->getUser()['rank_level'])
  { ?>
    <div class="alert alert-danger" role="alert">
      <?= $this->getUser()['name'] ?>
      is new and has not been ranked yet, check back in 24 hours.
    </div>
  <? } ?>
  <h1>
    <img src="<?= $this->getUser()['avatar_large'] ?>" alt="" class="avatar"/>
    <?= $this->getUser()['name']; ?>
    <small>
      <?= $this->getUser()['real_name']; ?>
      <?= $this->getCountryFlag($this->getUser()['country']) ?>
    </small>
    <a href="<?= $this->getUser()['profile'] ?>" target="_blank">
      <img src="/img/steam_square.png" alt="" class="steam pull-right"/>
    </a>
  </h1>
</div>

<?= $this->getAd() ?>

<?= $this->getXpBar() ?>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Stats</h3>
  </div>
  <table class="table" style="table-layout: fixed">
    <thead>
    <tr>
      <th width="15%"></th>
      <th width="15%">Level</th>
      <th width="15%">Games</th>
      <th width="15%">Badges</th>
      <th width="15%">Friends</th>
      <th width="25%">Time</th>
    </tr>
    </thead>
    <tbody>
    <?= $this->getValueRow() ?>
    <?= $this->getRankRow() ?>
    <?= $this->getPercentileRow() ?>
    </tbody>
  </table>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Info</h3>
  </div>
  <div class="panel-body">

    <table class="table table-condensed table-details">
      <tr>
        <td>Games Played</td>
        <td><?= $this->getGamesPlayed() ?></td>
      </tr>
      <tr>
        <td>Time on Steam</td>
        <td>
          <?= $this->getMinutes(time() - $this->getUser()['time_on_steam']) ?>
        </td>
      </tr>
      <tr>
        <td>Last Updated</td>
        <td>
          <?= $this->getMinutes(
            time() - strtotime($this->getUser()['updated_at'])
          ) ?>
        </td>
      </tr>
    </table>

  </div>
</div>

<div class="row">
  <?php
  $show = 20;
  $i = 1;
  if(is_array($this->getUser()['games_json']))
  {
    foreach($this->getUser()['games_json'] as $game => $time)
    {

      $hidden = ($time == 0 || $i > $show) ? 'hidden' : '';
      ?>
      <div
        class="col-xs-12 col-sm-6 col-md-4 col-lg-3 game-div <?= $hidden ? 'hidden' : '' ?>">
        <p>
          <?= $this->getMinutes($time * 60) ?><br/>
          <a href="/apps/<?= $game ?>">
            <img
              <?= $hidden ? 'data-' : '' ?>src="http://cdn.akamai.steamstatic.com/steam/apps/<?= $game ?>/header.jpg"
              class="game"/>
          </a>
        </p>
      </div>
      <?php
      $i++;
    }
  }
  ?>
</div>

<?php
if($this->getUser()['games'] > count(
    array_filter($this->getUser()['games_json'])
  ) || $this->getUser()['games'] > $show
)
{
  ?>
  <button type="button" class="btn btn-primary btn-xs pull-right"
          id="show-all-games">Show all games
  </button>
<?php } ?>
