<?php
/**
 * @var \Jleagle\Steam\Application\Views\UserListView $this
 */

use Jleagle\Steam\Application\Enums\SortFieldEnum;

?>

<div class="page-header">
  <h1>
    Users
    <small class="pull-right"><?= $this->getCount() ?> Users</small>
  </h1>
</div>

<?= $this->getAd() ?>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th width="1%">Rank</th>
      <th colspan="2">Player</th>
      <th><a href="/users/<?= SortFieldEnum::LEVEL ?>">Level</a></th>
      <th><a href="/users/<?= SortFieldEnum::GAMES ?>">Games</a></th>
      <th><a href="/users/<?= SortFieldEnum::BADGES ?>">Badges</a></th>
      <th><a href="/users/<?= SortFieldEnum::TIME ?>">Time (Min)</a></th>
      <th><a href="/users/<?= SortFieldEnum::FRIENDS ?>">Friends</a></th>
      <th width="10%">Country</th>
    </tr>
    </thead>
    <tbody data-p="<?= $this->getPage() ?>" data-o="<?= $this->getOrder() ?>">
    </tbody>
  </table>
</div>
